GET http://localhost:3001/api/blogs

###

GET http://localhost:3001/api/blogs?search=react

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFAYi5jb20iLCJpZCI6MywiaWF0IjoxNzc5MTY2MjI1fQ.5C-VNo8EGug53EID3XDZxlaaz9LAaMoL5z7oI7pMBp4

{
  "author": "React hey",
  "url": "Test",
  "title": "Test Title",
  "year": "2001"
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFAYi5jb20iLCJpZCI6MywiaWF0IjoxNzc5MTY2MjI1fQ.5C-VNo8EGug53EID3XDZxlaaz9LAaMoL5z7oI7pMBp4

{
  "author": "Outer",
  "url": "Test",
  "title": "Join Table Test",
  "year": "2026"
}

###

DELETE http://localhost:3001/api/blogs/26
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFAYi5mb28iLCJpZCI6MiwiaWF0IjoxNzc4OTMxMDE1fQ.pe-1JdFPG6bVFIRX2kFbxBWLxHavRxuKETKxSIeymu0

###

PUT http://localhost:3001/api/blogs/2
Content-Type: application/json

{
  "likes": "5"
}