GET http://localhost:3001/api/users

###

GET http://localhost:3001/api/users/3

###

GET http://localhost:3001/api/users/3?read=true

###

GET http://localhost:3001/api/users/3?read=false

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "a@b.com",
  "name": "aaa",
  "password": "bbb"
}

###

PUT http://localhost:3001/api/users/test
Content-Type: application/json

{
  "username": "hello"
}

###

PUT http://localhost:3001/api/users/hello
Content-Type: application/json

{
  "username": "test"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "a@b.com",
  "password": "bbb"
}